base_url = "/"

compile_sass = true

build_search_index = false

theme = "even"

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "nord"

[extra]
katex_enable = true
katex_auto_render = true
even_title = "nonl"
